android {
    signingConfigs {
        angleai {
            keyAlias 'angleai'
            keyPassword 'angleai'
            storeFile file('angleai.jks')
            storePassword 'angleai'
        }
    }

    flavorDimensions "version"

    productFlavors {
        angleai {
            dimension 'version'
            applicationId "com.angleai.buzzlp"
            signingConfig signingConfigs.angleai
        }
    }
}
